[package]
name = "blockchain"
version = "0.1.0"
authors = ["Chris Meyering <christophe.meyering@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = { path = "../crypto", version = "0.1.0" }