[package]
name = "crypto"
version = "0.1.0"
authors = ["Chris Meyering <christophe.meyering@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
sha2 = "0.8.1"
x25519-dalek = "0.6.0"
